POST  http://localhost:4000/employee
Content-Type: application/json
Accept: */*

{
    "firstName" :"pratik", 
    "lastName" :"singh", 
    "password" :"keepguessing", 
    "email" :"pratik@gmailcom",
    "phone" :7788996655
}

### 
POST http://localhost:4000/authenticate 
Content-Type: application/json
Accept: */*

{
    "email":"pratik@gmailcom", 
    "password" :"keepguessing"

}
